# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mzherlygin/arch/arch_lab-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mzherlygin/arch/arch_lab-main/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mzherlygin/arch/arch_lab-main/build/CMakeFiles /home/mzherlygin/arch/arch_lab-main/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mzherlygin/arch/arch_lab-main/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named auth_service

# Build rule for target.
auth_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 auth_service
.PHONY : auth_service

# fast build rule for target.
auth_service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/build
.PHONY : auth_service/fast

#=============================================================================
# Target rules for targets named user_service

# Build rule for target.
user_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 user_service
.PHONY : user_service

# fast build rule for target.
user_service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/build
.PHONY : user_service/fast

#=============================================================================
# Target rules for targets named product_service

# Build rule for target.
product_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 product_service
.PHONY : product_service

# fast build rule for target.
product_service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/build
.PHONY : product_service/fast

#=============================================================================
# Target rules for targets named event_listener

# Build rule for target.
event_listener: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 event_listener
.PHONY : event_listener

# fast build rule for target.
event_listener/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/build
.PHONY : event_listener/fast

auth_main.o: auth_main.cpp.o
.PHONY : auth_main.o

# target to build an object file
auth_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/auth_main.cpp.o
.PHONY : auth_main.cpp.o

auth_main.i: auth_main.cpp.i
.PHONY : auth_main.i

# target to preprocess a source file
auth_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/auth_main.cpp.i
.PHONY : auth_main.cpp.i

auth_main.s: auth_main.cpp.s
.PHONY : auth_main.s

# target to generate assembly for a file
auth_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/auth_main.cpp.s
.PHONY : auth_main.cpp.s

config/config.o: config/config.cpp.o
.PHONY : config/config.o

# target to build an object file
config/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/config/config.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/config/config.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/config/config.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/config/config.cpp.o
.PHONY : config/config.cpp.o

config/config.i: config/config.cpp.i
.PHONY : config/config.i

# target to preprocess a source file
config/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/config/config.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/config/config.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/config/config.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/config/config.cpp.i
.PHONY : config/config.cpp.i

config/config.s: config/config.cpp.s
.PHONY : config/config.s

# target to generate assembly for a file
config/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/config/config.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/config/config.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/config/config.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/config/config.cpp.s
.PHONY : config/config.cpp.s

database/cache.o: database/cache.cpp.o
.PHONY : database/cache.o

# target to build an object file
database/cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/database/cache.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/cache.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/cache.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/database/cache.cpp.o
.PHONY : database/cache.cpp.o

database/cache.i: database/cache.cpp.i
.PHONY : database/cache.i

# target to preprocess a source file
database/cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/database/cache.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/cache.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/cache.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/database/cache.cpp.i
.PHONY : database/cache.cpp.i

database/cache.s: database/cache.cpp.s
.PHONY : database/cache.s

# target to generate assembly for a file
database/cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/database/cache.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/cache.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/cache.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/database/cache.cpp.s
.PHONY : database/cache.cpp.s

database/database.o: database/database.cpp.o
.PHONY : database/database.o

# target to build an object file
database/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/database/database.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/database.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/database.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/database/database.cpp.o
.PHONY : database/database.cpp.o

database/database.i: database/database.cpp.i
.PHONY : database/database.i

# target to preprocess a source file
database/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/database/database.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/database.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/database.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/database/database.cpp.i
.PHONY : database/database.cpp.i

database/database.s: database/database.cpp.s
.PHONY : database/database.s

# target to generate assembly for a file
database/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/database/database.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/database.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/database.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/database/database.cpp.s
.PHONY : database/database.cpp.s

database/product.o: database/product.cpp.o
.PHONY : database/product.o

# target to build an object file
database/product.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/product.cpp.o
.PHONY : database/product.cpp.o

database/product.i: database/product.cpp.i
.PHONY : database/product.i

# target to preprocess a source file
database/product.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/product.cpp.i
.PHONY : database/product.cpp.i

database/product.s: database/product.cpp.s
.PHONY : database/product.s

# target to generate assembly for a file
database/product.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/product.cpp.s
.PHONY : database/product.cpp.s

database/user.o: database/user.cpp.o
.PHONY : database/user.o

# target to build an object file
database/user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/database/user.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/user.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/user.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/database/user.cpp.o
.PHONY : database/user.cpp.o

database/user.i: database/user.cpp.i
.PHONY : database/user.i

# target to preprocess a source file
database/user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/database/user.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/user.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/user.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/database/user.cpp.i
.PHONY : database/user.cpp.i

database/user.s: database/user.cpp.s
.PHONY : database/user.s

# target to generate assembly for a file
database/user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auth_service.dir/build.make CMakeFiles/auth_service.dir/database/user.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/user.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/database/user.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/database/user.cpp.s
.PHONY : database/user.cpp.s

event_main.o: event_main.cpp.o
.PHONY : event_main.o

# target to build an object file
event_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/event_main.cpp.o
.PHONY : event_main.cpp.o

event_main.i: event_main.cpp.i
.PHONY : event_main.i

# target to preprocess a source file
event_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/event_main.cpp.i
.PHONY : event_main.cpp.i

event_main.s: event_main.cpp.s
.PHONY : event_main.s

# target to generate assembly for a file
event_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_listener.dir/build.make CMakeFiles/event_listener.dir/event_main.cpp.s
.PHONY : event_main.cpp.s

product_main.o: product_main.cpp.o
.PHONY : product_main.o

# target to build an object file
product_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/product_main.cpp.o
.PHONY : product_main.cpp.o

product_main.i: product_main.cpp.i
.PHONY : product_main.i

# target to preprocess a source file
product_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/product_main.cpp.i
.PHONY : product_main.cpp.i

product_main.s: product_main.cpp.s
.PHONY : product_main.s

# target to generate assembly for a file
product_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/product_service.dir/build.make CMakeFiles/product_service.dir/product_main.cpp.s
.PHONY : product_main.cpp.s

user_main.o: user_main.cpp.o
.PHONY : user_main.o

# target to build an object file
user_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/user_main.cpp.o
.PHONY : user_main.cpp.o

user_main.i: user_main.cpp.i
.PHONY : user_main.i

# target to preprocess a source file
user_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/user_main.cpp.i
.PHONY : user_main.cpp.i

user_main.s: user_main.cpp.s
.PHONY : user_main.s

# target to generate assembly for a file
user_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/user_main.cpp.s
.PHONY : user_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... auth_service"
	@echo "... event_listener"
	@echo "... product_service"
	@echo "... user_service"
	@echo "... auth_main.o"
	@echo "... auth_main.i"
	@echo "... auth_main.s"
	@echo "... config/config.o"
	@echo "... config/config.i"
	@echo "... config/config.s"
	@echo "... database/cache.o"
	@echo "... database/cache.i"
	@echo "... database/cache.s"
	@echo "... database/database.o"
	@echo "... database/database.i"
	@echo "... database/database.s"
	@echo "... database/product.o"
	@echo "... database/product.i"
	@echo "... database/product.s"
	@echo "... database/user.o"
	@echo "... database/user.i"
	@echo "... database/user.s"
	@echo "... event_main.o"
	@echo "... event_main.i"
	@echo "... event_main.s"
	@echo "... product_main.o"
	@echo "... product_main.i"
	@echo "... product_main.s"
	@echo "... user_main.o"
	@echo "... user_main.i"
	@echo "... user_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

